### ISSUE TITLE
Build error in BooleanQueryANDInternals.java

### ISSUE THREAD

**Issue by sumanshil** [msfroh/lucene-university#14]
I am seeing the following error 

`
$ ./gradlew build

> Task :compileJava FAILED
/Users/sshil/lucene-university/src/main/java/example/basic/BooleanQueryANDInternals.java:153: error: BinaryAndWeight is not abstract and does not override abstract method scorerSupplier(LeafReaderContext) in Weight
    private static class BinaryAndWeight extends Weight {
                   ^
/Users/sshil/lucene-university/src/main/java/example/basic/BooleanQueryANDInternals.java:183: error: scorer(LeafReaderContext) in BinaryAndWeight cannot override scorer(LeafReaderContext) in Weight
        public Scorer scorer(LeafReaderContext context) throws IOException {
                      ^
  overridden method is final
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 449ms
1 actionable task: 1 executed

$ ./gradlew --version

------------------------------------------------------------
Gradle 8.5
------------------------------------------------------------

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.1 (Oracle Corporation 21.0.1+12-LTS-29)
OS:           Mac OS X 14.5 aarch64
`

**Comment by msfroh** [comment]
Ahh... right! Lucene used to require `Weight` implementations to provide `scorer()` and by default `scorerSupplier()` would delegate to `scorer()`. Starting with Lucene 10, it's the other way around. 

Thanks for catching that!

**Comment by msfroh** [comment]
Fixed it: https://github.com/msfroh/lucene-university/commit/4465459aa8eae2645a124cb86f21fea7682a5192

**Comment by msfroh** [comment]
Whoops! I pushed too soon. This should fix my bad fix: https://github.com/msfroh/lucene-university/commit/a96dd376c03ed37fffa466c182a84e9f53cbb5e8

**Comment by msfroh** [comment]
@sumanshil -- Please let me know if it's working for you with those changes.

Thanks again for reporting the failure!

**Comment by sumanshil** [comment]
@msfroh It is working now. Thanks for providing a quick fix.
