### ISSUE TITLE
Add a basic doc values example

### ISSUE THREAD

**Issue by msfroh** [msfroh/lucene-university#4]
Write an example that stores some doc values and uses them during a search. 

Maybe do a low-level (i.e. no `IndexSearcher`) example of searching with a field sort?

**Comment by reta** [comment]
@msfroh mind I pick this one? I have a few blind spots with doc values which I would like to figure out, and that sounds like a good contribution ... :-)

**Comment by msfroh** [comment]
Yes please! Thanks a lot @reta.

**Comment by reta** [comment]
I think we could close this one (I sadly cannot), thanks @msfroh !
